version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - browser-tools/install-chrome
      #- browser-tools/install-chromedriver
      - run:
          name: Install Gradle
          command: |
            wget https://github.com/gradle/gradle-distributions/releases/download/v8.5.0/gradle-8.5-bin.zip
            sudo mkdir -p /opt/gradle
            sudo unzip -o -d /opt/gradle gradle-8.5-bin.zip
            echo 'export PATH=$PATH:/opt/gradle/gradle-8.5/bin' >> $BASH_ENV
            source $BASH_ENV
            gradle --version
      - run:
          name: Install dependencies
          command: gradle dependencies
      - run:
          name: Run Selenium TestNG tests
          command: gradle test
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/reports/tests
          destination: test-reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - test